twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'form/fields.html.twig'
    # form_themes: ['bootstrap_5_horizontal_layout.html.twig']
    # form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        profiles: '%profiles%'

when@test:
    twig:
        strict_variables: true
