controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# app_index: # the route's name
#     path: / # the path
#     controller: App\Controller\HelloController::index # the controller related
#     # to the route - It should always be the fully qualified class name of the class
